import pandas as pd

conv = {
       'categorie' : (
        ['[PRS]', '[ETU]', '[APS]', '[ETA]', '[FON]', '[PRE]', '[AUS]',
            '[PMO]', '[VET]', '[VPM]', '[SAN]', '[AGR]', '[LOG]', '[ADU]'],
        ['Professionnel de santé', 'Etudiant',
            'Association professionnel de santé', 'Etablissement de santé',
            'Académies, Fondation, sociétés savantes, organismes de conseils',
            'Presse et média', 'Association usager de santé',
            'Personnes morales assurant la formation initiale ou continue des professionnels de santé',
            'Vétérinaire', 'Vétérinaire Personne Morale',
            'Groupement sanitaire', 'Groupement professionels agricoles',
            'Editeur de logiciel', "Association d'étudiants"]
        ),
    'qualite' : (
        ['[21]', '[60]', '[10]', '[95]', '[50]', '[02]', '[94]',
        '[01]', '[80]', '[70]', '[98]', '[40]', '[86]', '[03]', '[04]',
        '[96]', '[91]', '[28]', '[92]', '[ADE]', '[82]', '[05]', '[99]',
        '[EDP]'],
        ['Pharmacien', 'Infirmier', 'Médecin', 'Diététicien',
        'Sage-femme', 'Aide soignant', 'Ergothérapeute',
        'Préparateur en pharmacie et préparateur en pharmacie hospitalière',
        'Pédicure-podologue', 'Masseur-kinésithérapeute',
        'Manipulateur d’électroradiologie médicale', 'Chirurgien-dentiste',
        'Technicien de laboratoire médical', 'Auxiliaire de puériculture',
        'Ambulancier', 'Psychomotricien', 'Orthophoniste',
        'Opticien-lunetier', 'Orthoptiste', 'Assistant dentaire',
        'Prothésiste et orthésiste pour l’appareillage des personnes handicapées',
        'Audioprothésiste', 'Physicien médical', 'Editeur de presse']
	),
    'pays' : (
        ['[FR]', '[RE]', '[GP]', '[MQ]', '[GF]', '[YT]', '[BE]',
        '[DE]', '[MO]', '[NC]', '[AF]', '[MC]', '[TN]', '[CH]', '[ES]',
        '[GB]', '[PF]', '[GY]', '[US]', '[CA]', '[AT]', '[NL]', '[MR]',
        '[CZ]', '[IT]', '[TH]', '[SN]', '[SE]', '[CN]', '[LU]', '[BS]',
        '[NA]', '[DZ]', '[IL]', '[PL]', '[FI]', '[TR]', '[GM]', '[GA]',
        '[PK]', '[PS]', '[AD]', '[EG]', '[SY]', '[PA]', '[TO]', '[HK]',
        '[MX]', '[MA]', '[SI]', '[AR]', '[ST]', '[HU]', '[CF]', '[AL]',
        '[CM]', '[VA]', '[EE]', '[MD]', '[RO]', '[SA]', '[BF]', '[VN]',
        '[RS]', '[MG]', '[SK]', '[NR]', '[FJ]', '[CI]', '[IE]', '[DK]',
        '[LA]', '[MF]', '[BR]', '[NZ]', '[KH]', '[BG]', '[GE]', '[PM]',
        '[GN]', '[GR]', '[PT]', '[LB]', '[CG]', '[BJ]', '[IS]', '[UA]',
        '[TW]', '[ML]', '[CY]', '[PR]', '[IN]', '[MN]', '[CO]', '[RU]',
        '[PE]', '[AE]'],
        ['FRANCE','RÉUNION', 'GUADELOUPE', 'MARTINIQUE',
        'GUYANE FRANÇAISE', 'MAYOTTE', 'BELGIQUE', 'ALLEMAGNE', 'MACAO',
        'NOUVELLE-CALÉDONIE', 'AFGHANISTAN', 'MONACO', 'TUNISIE', 'SUISSE',
        'ESPAGNE', 'ROYAUME-UNI', 'POLYNÉSIE FRANÇAISE', 'GUYANA',
        'ÉTATS-UNIS', 'CANADA', 'AUTRICHE', 'PAYS-BAS', 'MAURITANIE',
        'TCHÈQUE, RÉPUBLIQUE', 'ITALIE', 'THAÏLANDE', 'SÉNÉGAL', 'SUÈDE',
        'CHINE', 'LUXEMBOURG', 'BAHAMAS', 'NAMIBIE', 'ALGÉRIE', 'ISRAËL',
        'POLOGNE', 'FINLANDE', 'TURQUIE', 'GAMBIE', 'GABON', 'PAKISTAN',
        'PALESTINE, ÉTAT DE', 'ANDORRE', 'ÉGYPTE',
        'SYRIENNE, RÉPUBLIQUE ARABE', 'PANAMA', 'TONGA', 'HONG KONG',
        'MEXIQUE', 'MAROC', 'SLOVÉNIE', 'ARGENTINE',
        'SAO TOMÉ-ET-PRINCIPE', 'HONGRIE', 'CENTRAFRICAINE, RÉPUBLIQUE',
        'ALBANIE', 'CAMEROUN', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)',
        'ESTONIE', 'MOLDOVA, RÉPUBLIQUE DE', 'ROUMANIE', 'ARABIE SAOUDITE',
        'BURKINA FASO', 'VIET NAM', 'SERBIE', 'MADAGASCAR', 'SLOVAQUIE',
        'NAURU', 'FIDJI', "CÔTE D'IVOIRE", 'IRLANDE', 'DANEMARK',
        'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE',
        'SAINT-MARTIN(PARTIE FRANÇAISE)', 'BRÉSIL', 'NOUVELLE-ZÉLANDE',
        'CAMBODGE', 'BULGARIE', 'GÉORGIE', 'SAINT-PIERRE-ET-MIQUELON',
        'GUINÉE', 'GRÈCE', 'PORTUGAL', 'LIBAN', 'CONGO', 'BÉNIN',
        'ISLANDE', 'UKRAINE', 'TAÏWAN, PROVINCE DE CHINE', 'MALI',
        'CHYPRE', 'PORTO RICO', 'INDE', 'MONGOLIE', 'COLOMBIE',
        'RUSSIE, FÉDÉRATION DE', 'PÉROU', 'ÉMIRATS ARABES UNIS']
    ),
    'titre' : (
        ['[PR]', '[DR]', '[AUTRE]', '[PG]', '[MG]', '[PC]', '[MC]'],
        ['Professeur', 'Docteur', 'Autre', 'Pharmacien Général',
        'Médecin Général', 'Pharmacien Chef', 'Médecin chef']
    ),
    'specialite' : (
	['[SM36]', '[SM32]', '[SM38]', '[SM41]', '[AUTRE]', '[SM16]',
       '[SM54]', '[SM15]', '[SM04]', '[SM03]', '[SM24]', '[SM27]',
       '[SM21]', '[SM40]', '[SM18]', '[SM17]', '[SM02]', '[SM30]',
       '[SM48]', '[SM29]', '[SM08]', '[SM14]', '[SM49]', '[SM10]',
       '[SM05]', '[SM34]', '[SM26]', '[SM55]', '[SM19]', '[SM45]',
       '[SM39]', '[SCD03]', '[SM01]', '[SM25]', '[SCD02]', '[SM44]',
       '[SM12]', '[SM09]', '[SM22]', '[SM13]', '[SM42]', '[SM46]',
       '[SM23]', '[SM35]', '[SP04]', '[SM53]', '[SM37]', '[SP03]',
       '[SM43]', '[SM20]', '[SM31]', '[SM06]', '[SM07]', '[SM11]',
       '[SM28]', '[SM50]', '[SM47]', '[SP02]', '[SCD01]', '[SM51]',
       '[SM52]', '[SM99]', '[SM33]', '[SP01]'],
	['Oncologie option médicale', 'Neurologie', 'Ophtalmologie',
       'Pneumologie', 'Autre', 'Endocrinologie et métabolisme',
       'Médecine Générale', 'Dermatologie et vénéréologie',
       'Cardiologie et maladies vasculaires', 'Biologie médicale',
       'Gastro-entérologie et hépatologie', 'Médecine interne',
       'Hématologie', 'Pédiatrie', 'Gériatrie', 'Génétique médicale',
       'Anesthesie-réanimation', 'Néphrologie', 'Rhumatologie',
       'Médecine physique et réadaptation',
       'Chirurgie orthopédique et traumatologie',
       'Chirurgie viscérale et digestive',
       'Santé publique et médecine sociale',
       'Chirurgie plastique reconstructrice et esthétique',
       'Chirurgie générale', 'O.R.L et chirurgie cervico faciale',
       'Qualifié en Médecine Générale',
       'Radio-diagnostic et Radio-Thérapie', 'Gynécologie médicale',
       'Radio-thérapie ', 'Oto-rhino-laryngologie',
       'Médecine Bucco-Dentaire', 'Anatomie et cytologie pathologiques',
       'Médecine du travail', 'Chirurgie Orale', 'Radio-diagnostic',
       'Chirurgie urologique', 'Chirurgie infantile',
       'Hématologie (option Maladie du sang)', 'Chirurgie vasculaire',
       'Psychiatrie', 'Réanimation médicale',
       'Hématologie (option Onco-hématologie)',
       'Oncologie (option onco-hématologie)', 'Hémovigilance',
       'Spécialiste en Médecine Générale',
       'Oncologie option radiothérapie', 'Pharmacovigilance',
       'Psychiatrie option enfant & adolescent',
       'Gynécologie-obstétrique', 'Neuro-chirurgie',
       'Chirurgie maxillo-faciale',
       'Chirurgie maxillo-faciale et stomatologie',
       'Chirurgie thoracique et cardio-vasculaire', 'Médecine nucléaire',
       'Stomatologie', 'Recherche médicale', 'Hygiène',
       'Orthopédie dento-faciale',
       'Gynéco-obstétrique et gynécologie médicale option 1',
       'Gynéco-obstétrique et gynécologie médicale option 2',
       'ORL et ophtalmologie', 'Neuro-psychiatrie', 'Radio-pharmacie']
    ),
    'identifiant' : (
        ['[RPPS]', '[AUTRE]', '[SIREN]', '[FINESS]', '[ORDRE]'],
        ['RPPS', 'AUTRE', 'SIREN', 'FINESS', 'ORDRE']
    )}
benef = {
       'categorie':(
              ['[PRS]', '[ETU]', '[FON]', '[VET]', '[PMO]', '[VPM]', '[APS]',
              '[AUS]', '[ETA]', '[PRE]', '[ADU]', '[LOG]', '[AGR]', '[SAN]'],
              ['Professionnel de santé', 'Etudiant',
              'Académies, Fondation, sociétés savantes, organismes de conseils',
              'Vétérinaire',
              'Personnes morales assurant la formation initiale ou continue des professionnels de santé',
              'Vétérinaire Personne Morale',
              'Association professionnel de santé',
              'Association usager de santé', 'Etablissement de santé',
              'Presse et média', "Association d'étudiants",
              'Editeur de logiciel', 'Groupement professionels agricoles',
              'Groupement sanitaire']
       ),
       'qualite':(
              ['[60]', '[10]', '[ADE]', '[21]', '[70]', '[50]', '[40]',
              '[01]', '[99]', '[82]', '[98]', '[94]', '[02]', '[86]', '[92]',
              '[96]', '[28]', '[95]', '[03]', '[04]', '[05]', '[91]', '[80]',
              '[EDP]'],
               ['Infirmier', 'Médecin', 'Assistant dentaire', 'Pharmacien',
              'Masseur-kinésithérapeute', 'Sage-femme', 'Chirurgien-dentiste',
              'Préparateur en pharmacie et préparateur en pharmacie hospitalière',
              'Physicien médical',
              'Prothésiste et orthésiste pour l’appareillage des personnes handicapées',
              'Manipulateur d’électroradiologie médicale', 'Ergothérapeute',
              'Aide soignant', 'Technicien de laboratoire médical',
              'Orthoptiste', 'Psychomotricien', 'Opticien-lunetier',
              'Diététicien', 'Auxiliaire de puériculture', 'Ambulancier',
              'Audioprothésiste', 'Orthophoniste', 'Pédicure-podologue',
              'Editeur de presse']
       ),
       'pays' : (
              ['[FR]', '[PF]', '[RE]', '[NC]', '[MQ]', '[GP]', '[GF]',
              '[BE]', '[DZ]', '[MC]', '[TN]', '[CH]', '[GY]', '[YT]', '[CA]',
              '[NZ]', '[IT]', '[US]', '[LU]', '[TH]', '[AF]', '[SL]', '[SN]',
              '[MA]', '[IL]', '[TR]', '[MF]', '[GB]', '[ES]', '[DE]', '[GD]',
              '[BL]', '[CI]', '[BJ]', '[MG]', '[SY]', '[MR]', '[GR]', '[EG]',
              '[FI]', '[RU]', '[BG]', '[BF]', '[GN]', '[NL]', '[NA]', '[PM]',
              '[JP]', '[FJ]', '[BD]', '[ZA]', '[LB]', '[PT]', '[PR]', '[SV]',
              '[GU]', '[MU]', '[AD]', '[GE]', '[DJ]', '[MY]', '[MZ]', '[KW]',
              '[SM]', '[CG]', '[OM]', '[BR]', '[RO]', '[ML]', '[AR]', '[CM]',
              '[IN]', '[GA]', '[VN]', '[RS]', '[VE]', '[CN]', '[TG]', '[CD]',
              '[TD]', '[KH]', '[MO]', '[CZ]', '[PY]', '[ST]', '[CF]', '[AE]',
              '[GM]', '[NR]', '[CL]', '[EC]', '[TF]', '[PG]', '[AL]', '[DK]',
              '[MD]', '[SA]', '[DM]', '[HU]', '[IE]', '[SK]'],
              ['FRANCE', 'POLYNÉSIE FRANÇAISE', 'RÉUNION',
              'NOUVELLE-CALÉDONIE', 'MARTINIQUE', 'GUADELOUPE',
              'GUYANE FRANÇAISE', 'BELGIQUE', 'ALGÉRIE', 'MONACO', 'TUNISIE',
              'SUISSE', 'GUYANA', 'MAYOTTE', 'CANADA', 'NOUVELLE-ZÉLANDE',
              'ITALIE', 'ÉTATS-UNIS', 'LUXEMBOURG', 'THAÏLANDE', 'AFGHANISTAN',
              'SIERRA LEONE', 'SÉNÉGAL', 'MAROC', 'ISRAËL', 'TURQUIE',
              'SAINT-MARTIN(PARTIE FRANÇAISE)', 'ROYAUME-UNI', 'ESPAGNE',
              'ALLEMAGNE', 'GRENADE', 'SAINT-BARTHÉLEMY', "CÔTE D'IVOIRE",
              'BÉNIN', 'MADAGASCAR', 'SYRIENNE, RÉPUBLIQUE ARABE', 'MAURITANIE',
              'GRÈCE', 'ÉGYPTE', 'FINLANDE', 'RUSSIE, FÉDÉRATION DE', 'BULGARIE',
              'BURKINA FASO', 'GUINÉE', 'PAYS-BAS', 'NAMIBIE',
              'SAINT-PIERRE-ET-MIQUELON', 'JAPON', 'FIDJI', 'BANGLADESH',
              'AFRIQUE DU SUD', 'LIBAN', 'PORTUGAL', 'PORTO RICO', 'EL SALVADOR',
              'GUAM', 'MAURICE', 'ANDORRE', 'GÉORGIE', 'DJIBOUTI', 'MALAISIE',
              'MOZAMBIQUE', 'KOWEÏT', 'SAINT-MARIN', 'CONGO', 'OMAN', 'BRÉSIL',
              'ROUMANIE', 'MALI', 'ARGENTINE', 'CAMEROUN', 'INDE', 'GABON',
              'VIET NAM', 'SERBIE', 'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU',
              'CHINE', 'TOGO', 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU', 'TCHAD',
              'CAMBODGE', 'MACAO', 'TCHÈQUE, RÉPUBLIQUE', 'PARAGUAY',
              'SAO TOMÉ-ET-PRINCIPE', 'CENTRAFRICAINE, RÉPUBLIQUE',
              'ÉMIRATS ARABES UNIS', 'GAMBIE', 'NAURU', 'CHILI', 'ÉQUATEUR',
              'TERRES AUSTRALES FRANÇAISES', 'PAPOUASIE-NOUVELLE-GUINÉE',
              'ALBANIE', 'DANEMARK', 'MOLDOVA, RÉPUBLIQUE DE', 'ARABIE SAOUDITE',
              'DOMINIQUE', 'HONGRIE', 'IRLANDE', 'SLOVAQUIE']
       ),
       'titre' :( 
              ['[DR]', '[PG]', '[PR]', '[MG]', '[AUTRE]', '[PC]', '[MC]'],
              ['Docteur', 'Pharmacien Général', 'Professeur',
              'Médecin Général', 'Autre', 'Pharmacien Chef', 'Médecin chef']
       ),
       'specialite' : (
              ['[SM54]', '[SM40]', '[SM03]', '[SM26]', '[SM39]', '[SM44]',
              '[SM02]', '[SM08]', '[SM53]', '[AUTRE]', '[SM04]', '[SM31]',
              '[SM11]', '[SM12]', '[SM05]', '[SM16]', '[SM13]', '[SM14]',
              '[SM25]', '[SM32]', '[SM41]', '[SM20]', '[SM15]', '[SM35]',
              '[SM24]', '[SM38]', '[SM36]', '[SM48]', '[SM45]', '[SM21]',
              '[SM27]', '[SM30]', '[SM99]', '[SM01]', '[SM19]', '[SM23]',
              '[SM43]', '[SCD01]', '[SM18]', '[SM42]', '[SM28]', '[SM17]',
              '[SM37]', '[SM55]', '[SM06]', '[SCD02]', '[SM34]', '[SM22]',
              '[SM29]', '[SM10]', '[SCD03]', '[SP02]', '[SM46]', '[SM09]',
              '[SM49]', '[SM51]', '[SP03]', '[SM50]', '[SM07]', '[SM52]',
              '[SM47]', '[SP01]', '[SM33]', '[SP04]'],
              ['Médecine Générale', 'Pédiatrie', 'Biologie médicale',
              'Qualifié en Médecine Générale', 'Oto-rhino-laryngologie',
              'Radio-diagnostic', 'Anesthesie-réanimation',
              'Chirurgie orthopédique et traumatologie',
              'Spécialiste en Médecine Générale', 'Autre',
              'Cardiologie et maladies vasculaires', 'Neuro-chirurgie',
              'Chirurgie thoracique et cardio-vasculaire',
              'Chirurgie urologique', 'Chirurgie générale',
              'Endocrinologie et métabolisme', 'Chirurgie vasculaire',
              'Chirurgie viscérale et digestive', 'Médecine du travail',
              'Neurologie', 'Pneumologie', 'Gynécologie-obstétrique',
              'Dermatologie et vénéréologie',
              'Oncologie (option onco-hématologie)',
              'Gastro-entérologie et hépatologie', 'Ophtalmologie',
              'Oncologie option médicale', 'Rhumatologie', 'Radio-thérapie ',
              'Hématologie', 'Médecine interne', 'Néphrologie',
              'ORL et ophtalmologie', 'Anatomie et cytologie pathologiques',
              'Gynécologie médicale', 'Hématologie (option Onco-hématologie)',
              'Psychiatrie option enfant & adolescent',
              'Orthopédie dento-faciale', 'Gériatrie', 'Psychiatrie',
              'Médecine nucléaire', 'Génétique médicale',
              'Oncologie option radiothérapie',
              'Radio-diagnostic et Radio-Thérapie', 'Chirurgie maxillo-faciale',
              'Chirurgie Orale', 'O.R.L et chirurgie cervico faciale',
              'Hématologie (option Maladie du sang)',
              'Médecine physique et réadaptation',
              'Chirurgie plastique reconstructrice et esthétique',
              'Médecine Bucco-Dentaire', 'Hygiène', 'Réanimation médicale',
              'Chirurgie infantile', 'Santé publique et médecine sociale',
              'Gynéco-obstétrique et gynécologie médicale option 1',
              'Pharmacovigilance', 'Stomatologie',
              'Chirurgie maxillo-faciale et stomatologie',
              'Gynéco-obstétrique et gynécologie médicale option 2',
              'Recherche médicale', 'Radio-pharmacie', 'Neuro-psychiatrie',
              'Hémovigilance']
       ),
       'identifiant' : (
              ['[AUTRE]', '[RPPS]', '[ORDRE]', '[SIREN]', '[FINESS]'],
              ['AUTRE', 'RPPS', 'ORDRE', 'SIREN', 'FINESS']
       )}
remu = {
       'categorie':(
              ['[APS]', '[PMO]', '[PRS]', '[PRE]', '[VET]', '[VPM]', '[FON]',
              '[ETA]', '[ETU]', '[AUS]', '[ADU]', '[SAN]', '[LOG]', '[AGR]'],
              ['Association professionnel de santé',
              'Personnes morales assurant la formation initiale ou continue des professionnels de santé',
              'Professionnel de santé', 'Presse et média', 'Vétérinaire',
              'Vétérinaire Personne Morale',
              'Académies, Fondation, sociétés savantes, organismes de conseils',
              'Etablissement de santé', 'Etudiant',
              'Association usager de santé', "Association d'étudiants",
              'Groupement sanitaire', 'Editeur de logiciel',
              'Groupement professionels agricoles']
       ),
       'qualite':(
              ['[10]', '[21]', '[60]', '[40]', '[92]', '[02]', '[98]',
              '[70]', '[99]', '[50]', '[80]', '[03]', '[95]', '[94]', '[28]',
              '[91]', '[ADE]', '[04]', '[86]', '[82]', '[01]', '[96]', '[05]'],
              ['Médecin', 'Pharmacien', 'Infirmier', 'Chirurgien-dentiste',
              'Orthoptiste', 'Aide soignant',
              'Manipulateur d’électroradiologie médicale',
              'Masseur-kinésithérapeute', 'Physicien médical', 'Sage-femme',
              'Pédicure-podologue', 'Auxiliaire de puériculture', 'Diététicien',
              'Ergothérapeute', 'Opticien-lunetier', 'Orthophoniste',
              'Assistant dentaire', 'Ambulancier',
              'Technicien de laboratoire médical',
              'Prothésiste et orthésiste pour l’appareillage des personnes handicapées',
              'Préparateur en pharmacie et préparateur en pharmacie hospitalière',
              'Psychomotricien', 'Audioprothésiste']
       ),
       'pays':(
              ['[FR]', '[GB]', '[GF]', '[CH]', '[MQ]', '[RE]', '[GP]',
              '[MC]', '[MO]', '[CZ]', '[NC]', '[NL]', '[AT]', '[AF]', '[BE]',
              '[PA]', '[DE]', '[YT]', '[PF]', '[MA]', '[ES]', '[FJ]', '[SK]',
              '[VA]', '[FI]', '[IT]', '[US]', '[LU]', '[SA]', '[IE]', '[CA]',
              '[PR]', '[ST]', '[GA]', '[SE]', '[PE]', '[TO]'],
              ['FRANCE', 'ROYAUME-UNI', 'GUYANE FRANÇAISE', 'SUISSE',
              'MARTINIQUE', 'RÉUNION', 'GUADELOUPE', 'MONACO', 'MACAO',
              'TCHÈQUE, RÉPUBLIQUE', 'NOUVELLE-CALÉDONIE', 'PAYS-BAS',
              'AUTRICHE', 'AFGHANISTAN', 'BELGIQUE', 'PANAMA', 'ALLEMAGNE',
              'MAYOTTE', 'POLYNÉSIE FRANÇAISE', 'MAROC', 'ESPAGNE', 'FIDJI',
              'SLOVAQUIE', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)',
              'FINLANDE', 'ITALIE', 'ÉTATS-UNIS', 'LUXEMBOURG',
              'ARABIE SAOUDITE', 'IRLANDE', 'CANADA', 'PORTO RICO',
              'SAO TOMÉ-ET-PRINCIPE', 'GABON', 'SUÈDE', 'PÉROU', 'TONGA']
       ),
       'titre':(
              ['[DR]', '[PR]', '[AUTRE]', '[PG]', '[MG]', '[MC]', '[PC]'],
              ['Docteur', 'Professeur', 'Autre', 'Pharmacien Général',
              'Médecin Général', 'Médecin chef', 'Pharmacien Chef']
       ),
       'specialite':(
              ['[AUTRE]', '[SM04]', '[SM12]', '[SM03]', '[SM48]', '[SM42]',
              '[SM45]', '[SM36]', '[SM24]', '[SM27]', '[SM35]', '[SM21]',
              '[SM49]', '[SM41]', '[SCD01]', '[SM28]', '[SM15]', '[SM34]',
              '[SM54]', '[SM31]', '[SM30]', '[SM16]', '[SCD02]', '[SM18]',
              '[SM02]', '[SM19]', '[SM08]', '[SM01]', '[SM20]', '[SM22]',
              '[SM29]', '[SM38]', '[SM05]', '[SM39]', '[SM10]', '[SM40]',
              '[SM32]', '[SM46]', '[SM13]', '[SM11]', '[SM14]', '[SM44]',
              '[SM26]', '[SM25]', '[SM07]', '[SM53]', '[SM47]', '[SM55]',
              '[SP03]', '[SM17]', '[SM37]', '[SP02]', '[SCD03]', '[SM23]',
              '[SM51]', '[SM43]', '[SM09]', '[SM50]', '[SM06]', '[SM52]',
              '[SM33]', '[SM99]', '[SP01]'],
              ['Autre', 'Cardiologie et maladies vasculaires',
              'Chirurgie urologique', 'Biologie médicale', 'Rhumatologie',
              'Psychiatrie', 'Radio-thérapie ', 'Oncologie option médicale',
              'Gastro-entérologie et hépatologie', 'Médecine interne',
              'Oncologie (option onco-hématologie)', 'Hématologie',
              'Santé publique et médecine sociale', 'Pneumologie',
              'Orthopédie dento-faciale', 'Médecine nucléaire',
              'Dermatologie et vénéréologie',
              'O.R.L et chirurgie cervico faciale', 'Médecine Générale',
              'Neuro-chirurgie', 'Néphrologie', 'Endocrinologie et métabolisme',
              'Chirurgie Orale', 'Gériatrie', 'Anesthesie-réanimation',
              'Gynécologie médicale', 'Chirurgie orthopédique et traumatologie',
              'Anatomie et cytologie pathologiques', 'Gynécologie-obstétrique',
              'Hématologie (option Maladie du sang)',
              'Médecine physique et réadaptation', 'Ophtalmologie',
              'Chirurgie générale', 'Oto-rhino-laryngologie',
              'Chirurgie plastique reconstructrice et esthétique', 'Pédiatrie',
              'Neurologie', 'Réanimation médicale', 'Chirurgie vasculaire',
              'Chirurgie thoracique et cardio-vasculaire',
              'Chirurgie viscérale et digestive', 'Radio-diagnostic',
              'Qualifié en Médecine Générale', 'Médecine du travail',
              'Chirurgie maxillo-faciale et stomatologie',
              'Spécialiste en Médecine Générale', 'Recherche médicale',
              'Radio-diagnostic et Radio-Thérapie', 'Pharmacovigilance',
              'Génétique médicale', 'Oncologie option radiothérapie', 'Hygiène',
              'Médecine Bucco-Dentaire', 'Hématologie (option Onco-hématologie)',
              'Gynéco-obstétrique et gynécologie médicale option 1',
              'Psychiatrie option enfant & adolescent', 'Chirurgie infantile',
              'Stomatologie', 'Chirurgie maxillo-faciale',
              'Gynéco-obstétrique et gynécologie médicale option 2',
              'Neuro-psychiatrie', 'ORL et ophtalmologie', 'Radio-pharmacie']
       ),
       'identifiant':(
              ['[AUTRE]', '[RPPS]', '[SIREN]', '[ORDRE]', '[FINESS]'],
              ['AUTRE', 'RPPS', 'SIREN', 'ORDRE', 'FINESS']
       )
}

codes = {}

def make_codes(data):
       for key in data.keys():
              if key not in codes.keys():
                     codes[key] = {}
              for i in range(0, len(data[key][0])):
                     if data[key][0][i] in codes[key]:
                            if codes[key][data[key][0][i]].strip() != data[key][1][i].strip():
                                   print('problem : %s - %s'%(codes[key][data[key][0][i]].strip(), data[key][1][i].strip()))
                     else:
                            codes[key][data[key][0][i]] = data[key][1][i].strip()

make_codes(conv)
make_codes(benef)
make_codes(remu)

import json
with open('codes.json', 'w', encoding='utf-8') as f:
    f.write(json.dumps(codes))